### ISSUE TITLE
Well this looks silly

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/events#15]
<img width="1440" alt="screen shot 2016-08-24 at 7 01 10 pm" src="https://cloud.githubusercontent.com/assets/1054558/17954082/593a0a2e-6a2d-11e6-92d0-fcc0c5c4fecc.png">

**Comment by 7imbrook** [comment]
-__- we get it

**Comment by wadeanthony0100** [comment]
Yeah, this is supposed to have a green theme...? @vuzDylan

**Comment by kristenmills** [comment]
@wadeanthony0100 shhhh

**Comment by wademauger** [comment]
🐑

**Comment by DanSwtmn** [comment]
Someone messed up....

**Comment by 7imbrook** [comment]
This has literally been GLP v3 for a year now

**Comment by kristenmills** [comment]
...

**Comment by 7imbrook** [comment]
Don't make me lock this issue, I think we can all have a civilized discussion here

**Comment by kristenmills** [comment]
Closing this as it looks fixed.
